// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio/CaseStudyAtlas.tsx": () => import("../components/mockups/portfolio/CaseStudyAtlas.tsx"),
  "./components/mockups/portfolio/CaseStudyPolished.tsx": () => import("../components/mockups/portfolio/CaseStudyPolished.tsx")
};
